# ================================
#     Item Attributes v1.3.1
# ================================

# Optional plugin intergration
PluginSupport:
  AdvancedEnchantments: true

# Items with this name cannot be fixed by /fix or /fix all, etc.
ItemFixBlacklist:
  - '&6&lSpecial Item'
